#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

wget https://dev.mysql.com/get/mysql-apt-config_0.8.5-1_all.deb
dpkg -i mysql-apt-config_0.8.5-1_all.deb
apt-get -y  update


apt-get --allow-unauthenticated -y install  libaio1 libmecab2;
apt-get --allow-unauthenticated  install -y mysql-common=5.7.11-0ubuntu6 mysql-client-core-5.7=5.7.11-0ubuntu6 mysql-client-5.7=5.7.11-0ubuntu6 mysql-server-core-5.7=5.7.11-0ubuntu6 mysql-server-5.7=5.7.11-0ubuntu6 percona-xtrabackup-24;

#wpercona-xtrabackup-24

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off
_EOF_

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]

!includedir /etc/mysql/conf.d/
_EOF_

if [ -f /etc/init/mysql.conf ]; then
    rm /etc/init/mysql.conf
fi

if [ ! -d  /var/run/mysqld ]
then
  mkdir /var/run/mysqld
fi

chown mysql /var/run/mysqld



systemctl daemon-reload
systemctl enable mysql

