#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'
apt-get -y  update


#apt-get --allow-unauthenticated -y install  libaio1 libmecab2;
#wget https://downloads.mysql.com/archives/get/file/mysql-server_5.7.13-1ubuntu16.04_amd64.deb-bundle.tar
#tar -xvf mysql-server_5.7.13-1ubuntu16.04_amd64.deb-bundle.tar
#dpkg -i mysql-common_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i mysql-community-client_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i mysql-client_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i mysql-community-server_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i mysql-server_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i libmysqlclient20_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i libmysqlclient-dev_5.7.13-1ubuntu16.04_amd64.deb
#dpkg -i libmysqld-dev_5.7.13-1ubuntu16.04_amd64.deb

#apt-get --allow-unauthenticated -y install percona-xtrabackup-24

apt-get --allow-unauthenticated -y install mysql-client-5.7 mysql-server-5.7 percona-xtrabackup-24

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off
_EOF_

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]

!includedir /etc/mysql/conf.d/
_EOF_

if [ -f /etc/init/mysql.conf ]; then
    rm /etc/init/mysql.conf
fi

if [ ! -d  /var/run/mysqld ]
then
  mkdir /var/run/mysqld
fi

chown mysql /var/run/mysqld



cat /etc/init.d/mysql > /etc/init.d/mysql.back

echo "

if [ ! -d  /var/run/mysqld ]
then
  mkdir /var/run/mysqld
fi

chown mysql /var/run/mysqld
" > /etc/init.d/mysql

cat /etc/init.d/mysql.back >> /etc/init.d/mysql
rm /etc/init.d/mysql.back

systemctl daemon-reload
systemctl enable mysql

